"""Emit a Delta Live Tables (DLT) pipeline from the IR.

Each IR step becomes an ``@dlt.table`` whose body returns a DataFrame. ``WHERE`` filters
on DATA steps are surfaced as ``@dlt.expect_or_drop`` data-quality expectations. Optional
Unity Catalog ``catalog``/``schema`` qualify the published table names.
"""

from __future__ import annotations

from ..ir import AggStep, DataStep, ModelStep, Program, SqlStep, StatStep, Step
from . import sparksql_emitter
from .base import safe_name


def emit(
    prog: Program,
    *,
    source_path: str = "",
    catalog: str | None = None,
    schema: str | None = None,
) -> str:
    target = ".".join(p for p in (catalog, schema) if p)
    out = [
        "# Databricks notebook source",
        "# Generated by sas2databricks -> target: Delta Live Tables",
        f"# Source: {source_path or '(in-memory)'}",
    ]
    if target:
        out.append(f"# Unity Catalog target: {target}")
    out += ["import dlt", "from pyspark.sql import functions as F", ""]
    for step in prog.steps:
        out.append(_table(step))
        out.append("")
    return "\n".join(out)


def _table(step: Step) -> str:
    name = safe_name(step.name)
    flag = "  # [REVIEW]" if step.prov.needs_review() else ""
    expectations = ""

    if isinstance(step, SqlStep):
        body = f'    return spark.sql("""{step.sql}""")'
    elif isinstance(step, (AggStep, DataStep, StatStep)):
        sql = sparksql_emitter._emit_step(step)
        if isinstance(step, DataStep) and step.where:
            expectations = f'@dlt.expect_or_drop("valid_rows", {step.where!r})\n'
        select = sql.split(" AS\n", 1)[-1].rstrip(";")
        body = f'    return spark.sql("""{select}""")'
    elif isinstance(step, ModelStep):
        body = (
            "    # MANUAL REVIEW: MLlib models are not DLT tables.\n"
            "    # Train via the PySpark target and register predictions as a table.\n"
            "    return spark.range(0)"
        )
    else:
        body = "    # MANUAL REVIEW: implement this DLT table body\n    return spark.range(0)"

    comment = f"SAS {step.kind}"
    return (
        f"{expectations}@dlt.table(name={name!r}, comment={comment!r}){flag}\n"
        f"def {name}():\n{body}"
    )
