"""Emit Spark SQL / Databricks SQL from the IR."""

from __future__ import annotations

from ..ir import AggStep, DataStep, ModelStep, Program, ReportStep, SqlStep, StatStep, Step
from .base import safe_name

_AGG_SQL = {
    "avg": "avg({c})",
    "sum": "sum({c})",
    "count": "count({c})",
    "min": "min({c})",
    "max": "max({c})",
    "stddev": "stddev({c})",
    "variance": "variance({c})",
    "percentile_approx_25": "percentile_approx({c}, 0.25)",
    "percentile_approx_50": "percentile_approx({c}, 0.50)",
    "percentile_approx_75": "percentile_approx({c}, 0.75)",
}


def emit(prog: Program, *, source_path: str = "") -> str:
    out = [
        "-- Generated by sas2databricks -> target: spark sql",
        f"-- Source: {source_path or '(in-memory)'}",
    ]
    for step in prog.steps:
        sql = _emit_step(step)
        if sql:
            out.append(f"\n-- step: {step.name} (conf={step.prov.confidence:.2f})\n{sql}")
    return "\n".join(out) + "\n"


def _emit_step(step: Step) -> str:
    if isinstance(step, SqlStep):
        view = safe_name(step.name)
        return f"CREATE OR REPLACE TEMP VIEW {view} AS\n{step.sql};"
    if isinstance(step, AggStep):
        return _agg(step)
    if isinstance(step, DataStep):
        return _data(step)
    if isinstance(step, ReportStep):
        cols = ", ".join(step.columns) if step.columns else "*"
        order = f"\nORDER BY {', '.join(step.group_by)}" if step.group_by else ""
        return f"SELECT {cols} FROM {safe_name(step.source) or 'src'}{order};"
    if isinstance(step, StatStep):
        return _stat(step)
    if isinstance(step, ModelStep):
        return (
            f"-- MANUAL REVIEW: PROC {step.estimator} has no Spark SQL equivalent.\n"
            f"-- Use the PySpark/DLT target for the MLlib {step.estimator} scaffold."
        )
    return f"-- MANUAL REVIEW: step `{step.name}` (kind={step.kind}) not emitted as SQL"


def _stat(step: StatStep) -> str:
    view = safe_name(step.name)
    src = safe_name(step.source) or "src"
    if step.op == "corr":
        cols = step.columns or []
        if step.with_columns:
            pairs = [(a, b) for a in cols for b in step.with_columns]
        else:
            pairs = [
                (cols[i], cols[j])
                for i in range(len(cols))
                for j in range(i + 1, len(cols))
            ]
        if not pairs:
            return f"-- PROC CORR for {src}: add VAR columns to compute correlations"
        selects = [
            f"SELECT '{a}' AS x, '{b}' AS y, corr({a}, {b}) AS corr FROM {src}"
            for a, b in pairs
        ]
        body = "\nUNION ALL\n".join(selects)
        return f"CREATE OR REPLACE TEMP VIEW {view} AS\n{body};"
    # univariate -> summary statistics
    cols = step.columns or ["*"]
    measures = []
    for c in cols:
        if c == "*":
            continue
        measures += [
            f"count({c}) AS {c}_n",
            f"avg({c}) AS {c}_mean",
            f"stddev({c}) AS {c}_std",
            f"min({c}) AS {c}_min",
            f"percentile_approx({c}, 0.5) AS {c}_median",
            f"max({c}) AS {c}_max",
        ]
    select = ",\n  ".join(measures) if measures else "count(*) AS n"
    return f"CREATE OR REPLACE TEMP VIEW {view} AS\nSELECT\n  {select}\nFROM {src};"


def _agg(step: AggStep) -> str:
    view = safe_name(step.name)
    src = safe_name(step.source) or "src"
    measures = []
    for m in step.measures:
        tmpl = _AGG_SQL.get(m.func, f"{m.func}({{c}})")
        col = "*" if m.column == "*" else m.column
        measures.append(tmpl.format(c=col) + f" AS {m.alias}")
    select_cols = list(step.group_by) + measures
    gb = f"\nGROUP BY {', '.join(step.group_by)}" if step.group_by else ""
    return (
        f"CREATE OR REPLACE TEMP VIEW {view} AS\n"
        f"SELECT {', '.join(select_cols)}\nFROM {src}{gb};"
    )


def _data(step: DataStep) -> str:
    view = safe_name(step.name)
    if step.merge:
        parts = [safe_name(m) for m in step.merge]
        if step.by:
            using = "(" + ", ".join(step.by) + ")"
            from_clause = parts[0]
            for other in parts[1:]:
                from_clause = f"{from_clause} FULL JOIN {other} USING {using}"
        else:
            from_clause = " CROSS JOIN ".join(parts)
        src = f"({from_clause})" if len(parts) > 1 else parts[0]
    else:
        src = safe_name(step.source) or "src"
    if step.needs_row_order:
        src = f"(SELECT *, monotonically_increasing_id() AS _row_id FROM {src})"
    cols = step.keep if step.keep else ["*"]
    select = ", ".join(cols)
    for a in step.assignments:
        if a.condition:
            select += f",\n  CASE WHEN {a.condition} THEN {a.expr} END AS {a.target}"
        else:
            select += f",\n  {a.expr} AS {a.target}"
    where = f"\nWHERE {step.where}" if step.where else ""
    return f"CREATE OR REPLACE TEMP VIEW {view} AS\nSELECT {select}\nFROM {src}{where};"
