"""Emit a SAS-vs-Spark data-parity validation notebook.

For every materialized output of the migrated program, the generated notebook compares
the Spark result against a reference dataset exported from SAS (CSV/Parquet) on three
axes: row count, schema (column names), and a per-column aggregate checksum. Differences
are collected into a summary DataFrame so a reviewer can see exactly where SAS and Spark
diverge before cutting over.
"""

from __future__ import annotations

from ..ir import FormatStep, MacroDef, ModelStep, Program, Step
from .base import safe_name

_HELPER = '''from pyspark.sql import functions as F

def compare_output(name, spark_df, ref_path, ref_format="parquet"):
    """Compare a migrated Spark output against its SAS reference export."""
    ref = spark.read.format(ref_format).option("header", True).option(
        "inferSchema", True).load(ref_path)
    results = []
    s_count, r_count = spark_df.count(), ref.count()
    results.append((name, "row_count", str(s_count), str(r_count), s_count == r_count))
    s_cols, r_cols = set(spark_df.columns), set(ref.columns)
    results.append((name, "schema", str(sorted(s_cols)), str(sorted(r_cols)),
                    s_cols == r_cols))
    for col in sorted(s_cols & r_cols):
        try:
            s_sum = spark_df.agg(F.sum(F.col(col).cast("double"))).first()[0]
            r_sum = ref.agg(F.sum(F.col(col).cast("double"))).first()[0]
            ok = (s_sum is None and r_sum is None) or (
                s_sum is not None and r_sum is not None and abs(s_sum - r_sum) < 1e-6)
            results.append((name, f"sum({col})", str(s_sum), str(r_sum), ok))
        except Exception as exc:  # non-numeric column
            results.append((name, f"sum({col})", "n/a", "n/a", True))
    return results
'''


def emit(
    prog: Program,
    *,
    source_path: str = "",
    ref_base: str = "/Volumes/main/sas_reference",
) -> str:
    out = [
        "# Databricks notebook source",
        "# Generated by sas2databricks -> target: data-parity validation",
        f"# Source: {source_path or '(in-memory)'}",
        "# Point ref_base at the folder holding SAS-exported reference datasets.",
        "",
        "# COMMAND ----------",
        "",
        _HELPER,
        "# COMMAND ----------",
        "",
        f'ref_base = "{ref_base}"',
        "all_results = []",
    ]
    for step in prog.steps:
        if isinstance(step, (FormatStep, MacroDef, ModelStep)):
            continue
        if not _produces_output(step):
            continue
        view = safe_name(step.name)
        out.append(
            f'all_results += compare_output("{view}", spark.table("{view}"), '
            f'f"{{ref_base}}/{view}")'
        )
    out += [
        "",
        "# COMMAND ----------",
        "",
        'summary = spark.createDataFrame(',
        '    all_results, ["output", "check", "spark", "sas", "match"])',
        'mismatches = summary.where(~F.col("match"))',
        'print(f"{mismatches.count()} mismatch(es) found")',
        "display(summary)",
        "",
    ]
    return "\n".join(out)


def _produces_output(step: Step) -> bool:
    return bool(step.name) and step.kind not in {"raw", "macro", "format", "model"}
